### ISSUE TITLE
[4.x] Import as default not working with typescript

### ISSUE THREAD

**Issue by etler** [algolia/algoliasearch-client-javascript#1000]
I've been trying to import the algolia library into a typescript project, and while the type definitions check out and compile fine, executing gets a reference error when it looks for the default export.

I am using the following code to import algolia:

```typescript
import algoliasearch from 'algoliasearch'
const algoliaClient = algoliasearch(algoliaId, algoliaAdminKey)
const algoliaIndex = algoliaClient.initIndex('categories')
```

That compiles to:

```javascript
const algoliasearch_1 = require("algoliasearch");
const algoliaClient = algoliasearch_1.default(config_1.algoliaId, config_1.algoliaAdminKey);
const algoliaIndex = algoliaClient.initIndex('categories');
```

However the CJS style export from algolia stored in `algoliasearch_1` which comes from `algoliasearch.cjs.js` has no default export set:

```javascript
module.exports = algoliasearch;
```

This is inconsistent with the typescript export declaration defined in `algoliasearch.d.ts`:

```typescript
declare function algoliasearch(appId: string, apiKey: string, options?: AlgoliaSearchOptions): SearchClient;

declare namespace algoliasearch {
    var version: string;
}
export default algoliasearch;
```

I was able to fix the error by adding an additional default export to support ES6 style default exports:

```javascript
module.exports = algoliasearch;
module.exports.default = module.exports;
```

I'm not sure how `algoliasearch` is being imported into other typescript projects. Without jumping through a ton of hoops, I could not find a clean way of importing the library.

**Comment by nunomaduro** [comment]
I will investigate this Monday morning. 👍

**Comment by nunomaduro** [comment]
In the normal world, we would have the `module` key pointing the ES imports to the correct ESM build. The problem here is that the we don't have a universal ESM build, as it depends from the environment.

Since we don't have the `module` key, ES imports in Node uses the `index.js` that points to the CommonJS build.

Using the `default` ES imports with CommonJS requires one of two things: 

1. The user using the code activate the flag [esModuleInterop flag](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) on your tsconfig file. In this case we need to document this.

2. Include a bug fix in our client index.js adding:

```diff
module.exports = require('./dist/algoliasearch.cjs.js');
+module.exports.default = require('./dist/algoliasearch.cjs.js');
```

@etler As workaround, I propose you to activate the flag [esModuleInterop flag](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) on your tsconfig file.

@yannickcr @Haroenv For us, we need to think if we want to do the bug fix in our client index.js.

**Comment by nunomaduro** [comment]
Note: this was already a problem on the `v3`.

**Comment by Haroenv** [comment]
Yes, adding the default exports for non-interop projects might be the best option to clear our bases

**Comment by nunomaduro** [comment]
@etler This issue has been fixed on the version `4.0.3`.

**Comment by jacob-qurika** [comment]
I'm on version 4.1.0 and I'm still getting this.

**Comment by nunomaduro** [comment]
@jacob-qurika Can you share the coding you are using?

**Comment by jacob-qurika** [comment]
I can try to create a minimal project when I find the time. For the time being, I am able to set esModuleInterop as a workaround.

**Comment by ersaurabh101** [comment]
npm install algoliasearch in my ionic project, it is continously giving me this error - `Cannot find name 'Omit'.
[ng] 203 export declare type WithoutCredentials<TClient> = Omit<TClient, 'appId' | 'apiKey'>;` 

Been 12 hours playing with this

I even added "esModuleInterop": true, in tsconfig.json but nothing is working for me

Any help will be really appretiated.

**Comment by Haroenv** [comment]
you need to be using at least TypeScript 3.8 @ersaurabh101
