### ISSUE TITLE
error Couldn't find package "@algolia/client-personalization@4.10.0" required by "algoliasearch@^4.8.6" on the "npm" registry.

### ISSUE THREAD

**Issue by joshunger** [algolia/algoliasearch-client-javascript#1286]
We're seeing this in our build logs.

error Couldn't find package "@algolia/client-personalization@4.10.0" required by "algoliasearch@^4.8.6" on the "npm" registry.

Also, this is returning 404 https://www.npmjs.com/package/@algolia/client-personalization

And

```
verbose 1.253948505 Request "https://registry.yarnpkg.com/@algolia%2fclient-personalization" finished with status code 404.
```

Thanks.

-josh

**Comment by kamami** [comment]
Same

**Comment by keichinger** [comment]
Can confirm, encountering the same error with the latest version.

Either the package is not yet published (and still private), or someone has (accidentally?) unpublished it.

**Comment by jodiedoubleday** [comment]
Yup same issue here

```npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@algolia%2fclient-personalization - Not found```

**Comment by keichinger** [comment]
My money is on „not yet published” as this dependency seems to be a new dependency in v4.10.0:

https://github.com/algolia/algoliasearch-client-javascript/blob/4.10.0/packages/algoliasearch/package.json#L34 vs https://github.com/algolia/algoliasearch-client-javascript/blob/4.9.3/packages/algoliasearch/package.json

So pinning the version to v4.9.3 works for now, until the new/renamed package has been made available :)

**Comment by francoischalifour** [comment]
I think this is due to an npm issue, seeing their [status page](https://status.npmjs.org/#past-incidents).

**Comment by oytuneyucel** [comment]
this is blocking docusaurus classic template install altogether

`npx @docusaurus/init@latest init my-website classic`

**Comment by Haroenv** [comment]
It's definitely published, however I'm not sure whether npm has actually processed it. How come nobody used lockfiles?

**Comment by keichinger** [comment]
> How come nobody used lockfiles?

I am using `package-lock.json`, however I was in the middle of upgrading all dependencies :D That's when I noticed it.

Since the initial `npm update` has failed, I removed the `node_modules` and `package-lock.json` (like I do every now and then) and then re-installed everything from scratch, to also make sure that it's really installable.

Honestly, to me this issue is not a big deal at all. Until NPM has sorted out its publishing state of said package, I'll just keep using the previous version. No biggie :)

**Comment by oytuneyucel** [comment]
> How come nobody used lockfiles?

Any method to create a lockfile on a fresh project that uses a package with `^` dependency? 🤔

**Comment by Haroenv** [comment]
I'm very sorry for the downtime this caused anyone, even though it said "published" for me, it did not mention the access was private (even though I ran `npm access public @algolia/client-personalization` and `npm access public @algolia/recommend`). Publishing a patch with --access public fixed it as far as I can tell.

Will make sure new packages in the future have a throwaway version published before relying on it, very sorry!

**Comment by keichinger** [comment]
@Haroenv thanks for your quick help! It's always a pleasure to work with you and the fine folks at Algolia ☺️ 

I can only speak for myself again: No harm, no foul, so don't worry =) If there were any learnings out of this, then it was already worth it ✌️

**Comment by kamami** [comment]
Thanks for the fast support!

**Comment by oytuneyucel** [comment]
amazing! thanks for the fix 🥳

**Comment by Haroenv** [comment]
Sorry again for the misunderstanding on what was actually going wrong here (I thought it was eventual consistency first, but it turned out to be never consistency)

https://www.npmjs.com/package/%40algolia%2Fclient-personalization and https://www.npmjs.com/package/%40algolia%2Frecommend now seem accessible from a private tab for me, and show as public on the package page:

<img width="1289" alt="Screenshot 2021-06-23 at 15 49 53" src="https://user-images.githubusercontent.com/6270048/123108957-2858cf80-d43b-11eb-803e-b196464d0c3e.png">
<img width="515" alt="Screenshot 2021-06-23 at 15 55 20" src="https://user-images.githubusercontent.com/6270048/123109332-71108880-d43b-11eb-9c98-7a54ee1da386.png">

**Comment by Haroenv** [comment]
Since npm caches really heavily, I recommend to install 4.9.3 if you have any issues with retrieving the 4.10.0 or 4.10.1 packages, but I'll close it, as it seems you're able to install it now.

**Comment by joshunger** [comment]
Thank you @Haroenv!!!
