### ISSUE TITLE
How to find multiple objects based on a objectID prefix?

### ISSUE THREAD

**Issue by akdj** [algolia/algoliasearch-client-javascript#1373]
Hello, 

I need to get a list of objects already published on Algolia, by querying with a objectID prefix, Is it possible?

**Comment by bodinsamuel** [comment]
Hello, 
this is not possible to query by objectID prefix. If the prefix are known in advance you could create a dedicated prop in your record, e.g:
```json
{
  "objectID": "foobar1234",
  "prefix": "foobar"
}
```

**Comment by akdj** [comment]
Hi @bodinsamuel 
Ok, I can add a dedicated prop for that. Then what method should I use to perform the finding?  I found `search`, `multipleQueries`, `findObject`, but I don't know which one should I use to get a list, and what parameter should I put in. 

Could you send me a code example?

**Comment by bodinsamuel** [comment]
In that case you can use `facets` so that you can group and filter using exact match.
https://www.algolia.com/doc/api-reference/api-parameters/facets/
https://www.algolia.com/doc/api-reference/api-parameters/filters/

If you want partial match you can use a regular field and search only on this field:
https://www.algolia.com/doc/api-reference/api-parameters/restrictSearchableAttributes/

I'll suggest to reach out to support@algolia.com for more advanced support 👍🏻
