### ISSUE TITLE
COR Issues

### ISSUE THREAD

**Issue by chethanbr25** [algolia/algoliasearch-client-javascript#1401]
I am facing CORS issue whenever i am trying to connect through non prod nextjs application.
It works fine with localhost.

Access to XMLHttpRequest at 'https://984xu93gqp-dsn.algolia.net/1/indexes/crawler_User%20Dev%20Site/query?x-algolia-agent=Algolia%20for%20JavaScript%20(4.13.0)%3B%20Browser%20(lite)&x-algolia-api-key=faa7907b7e141496d2a88664119732f4&x-algolia-application-id=984XU93GQP' from origin 'https://stage.dentalcare.com' has been blocked by CORS policy: Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by chethanbr25** [comment]
we are using  algoliasearch/lite' in nexjst frontend app. search was working fine a week ago with no issues and it started throwing the CORS- Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response.
We have not made any changes to HTTP Headers .
Steps to reproduce.
access the site https://stage.dentalcare.com/ and you should be able to see the error in the browser console.

**Comment by Haroenv** [comment]
It looks like some other script on the page is modifying `XMLHttpRequest` to add a couple headers (traceparent, Request-Id and Request-Context). From my googling this may be related to an analytics script like Microsoft ApplicationInsights. Algolia does not support these extra headers being sent, which is why they return with an error. 

Following https://github.com/microsoft/ApplicationInsights-JS#setting-up-autocollection and https://github.com/microsoft/ApplicationInsights-JS#configuration, you could use `disableAjaxTracking` in the configuration. As I don't see a way to disable just for some URLs, you could open an issue there: https://github.com/microsoft/ApplicationInsights-JS/issues (only if you actually use ApplicationInsights of course)

**Comment by chethanbr25** [comment]
Hi @Haroenv ,
Thank you for highlighting this issue. 
Yes this was happening because appinsights were trying to add couple of headers .
Now that we excluded algolia request from telemetry service it works fine.
This issue can be closed

**Comment by Haroenv** [comment]
Glad you found a solution, and I'm surprised this is only the first time I've seen an analytics client adding extra headers automatically, glad it's not more common!
