### ISSUE TITLE
Architecture of the retries / fallback strategies 

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-javascript#255]
After working on the code for the host switching (see #251 and #254), I found that the code handling the retries and the fallback were merged together. This makes the code very hard to read and even implement correctly. The fallback and the retries should be considered as two different levels and abstracted accordingly.

I think we should have the access, retries and fallback as three different layers. With each of them with a clear definition of their interaction.

Happy to help on that.

**Comment by vvo** [comment]
Taking PRS simplifying this code YES. We should have enough tests now to refactor this part without breaking anything and enough code review

**Comment by Haroenv** [comment]
So in v4 this will be handled in a separate part. I’ll write down some thoughts here to definitely not forget it when implementing. 

Every method in the client will have a `requester` as its first argument. This function will return a Promise when called with an 

```js
export type Method = 'POST' | 'GET' | 'DELETE' | 'PUT';
type RequestArguments = {
  method: Method,
  path: string,
  qs?: Object,
  body?: Object,
  options?: Object,
};

req(argument: RequestArguments);
```

This `requester` is also available as a property on `initIndex` etc. so that you can set and unset static `requestOptions` using `setOptions(current => next)`.

The `requester` is a result of the `createRequester` factory. It will take as arguments `appId`, `apiKey`, `defaultOptions` and lastly the `request`. That's a lot of "`request`", but the last function is the one that actually gets called, to be able to have different functions for XHR, Node, jQuery, Angular and possibly fetch. 

The actual request strategy, when to call the request function when the requester is called and which domain to call when is handled in a separate `class`, which is initialised inside `createRequester`.


P.S. you can convert Promises to callbacks with [`util.callbackify`](https://nodejs.org/api/util.html#util_util_callbackify_original)

**Comment by nunomaduro** [comment]
This `v4.0` is in progress, and we took into consideration all those points.
