### ISSUE TITLE
Add whether it's a mobile/desktop/node to the x-algolia-agent

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-javascript#492]
In order to analyse more efficiently from where our queries are coming from, we should add whether the JS API client is used from a mobile, a desktop or a backend source to the x-algolia-agent.

**Comment by vvo** [comment]
For Node.js it's already the case (we send a specific UA, but we do not put the nodejs version for instance).

For browser user agents it's a bit trickier, there's no specific mobile build.

What would be the device information we want to look for? Parsing user agents? Viewport width? Ultimately this can end up in some good code.

If we are gonna parse user agents, should we do it in the JavaScript lib or server side? Ultimately this information is available on our servers already.

**Comment by nunomaduro** [comment]
Normally we have already this information - since we use `x-algolia-user-agent` for our own user agent, the normal `x-user-agent` will contain information about the device, like this example: `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15`.

@Haroenv can you confirm? If yes - we can close this issue.

**Comment by Haroenv** [comment]
Yes, the regular user agent contains "this information" as good as we can (although it's still a bad idea to parse the regular user agent to find if it's movile)
