### ISSUE TITLE
No way to add and remove headers

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-client-javascript#571]
In some dashboard situations, @alexandremeunier would like to add and remove headers easily.

Right now we only have setExtraHeaders and it manipulates an array. So you can't do:

```js
client.setExtraHeader('...', '...');
client.unsetExtraHeader('...');
// or client.setExtraHeader('name', null); // this just adds currently
```

1. It should manipulate a map
2. It should have an unset

Can we make a patch in V3 for this? Thanks (that would be your first client release @Haroenv :D)

In V4 we don't have to think about this first, we will add it in some other way. (to be discussed)

**Comment by bobylito** [comment]
I often see in map related API that you also have a 3rd method to check if a value is set. Also I would be interested to get the actual value of a key, and this method could fit the previous API.

You said you want to use a map. Does this mean that you'd like to use the [native map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map) implementation or does it even matter? First impression is that it's an implementation detail.

However if we were to use an actual Map object, we could expose it directly as it has an already known (as in documented as a web standard API). Not sure that's the best for us, but this is a possibility :)

Since we are only handling http headers, it should be noted that the keys and the values are `string`

**Comment by Haroenv** [comment]
Using a `Map` might seem like a good idea, mostly because It's already polyfilled in the dashboard, and we're moving to a "Bring you own Polyfill" situation in V4, but I'm not convinced that this would be "allowed", since technically we support IE8 in the JS client. 

For reference, the support for `Map` is IE11/Edge, Chrome 38/51, Safari 7/10, Firefox 13/42  (there are several parts to the spec)

cc @alexandremeunier

**Comment by vvo** [comment]
We should move to a Map if it provides real benefits then yes. But the current mobile support is poor no?

![image](https://user-images.githubusercontent.com/123822/28308639-23a507de-6ba7-11e7-98f0-1d637643d12f.png)

I dunno about the implementation details right now, for V3 we need only a simple object.

**Comment by bobylito** [comment]
Well the benefit is an API that we don't have to invent. The cons is obviously that it is less nice in terms of doc. I would probably not go for that either (also the fact that you must bring a polyfill is not great)

However, I still think we need an accessor for values of the headers. WDYT?

**Comment by Haroenv** [comment]
Eh, it's implemented with a regular object now in a few minutes, I think this discussion isn't needed @bobylito :)

**Comment by vvo** [comment]
> However, I still think we need an accessor for values of the headers. WDYT?

There's now a getExtraHeader, but yes it was needed indeed

**Comment by Haroenv** [comment]
closed in https://github.com/algolia/algoliasearch-client-javascript/commit/0271935f48f04cb7575a6568d863c59e0f723800
