### ISSUE TITLE
name: "AlgoliaSearchError", message: "Unknown parameter:

### ISSUE THREAD

**Issue by balwant20** [algolia/algoliasearch-client-javascript#611]
I have two diffrent diffrent theme in my magento 1.9 store website.the algolia instant search working fine with one mageto theme but not worked for another one.there is something error called 400:bad request when i type anything in search box. i think there is somthing js file confilct.
can you plz figure out this problem or give suggestions which i can implement.
thanks in advance

**Comment by rayrutjes** [comment]
Hey @balwant20 ,

I think your issue is probably more specific to Magento than it is to the Algolia JS client.

Would you mind sending a quick email to support@algolia.com?
Please include a link to your website, the full stack trace, the name of the themes and the version of Magento you are using.
Also make sure to have the latest version of our Magento extension.

**Comment by balwant20** [comment]
Hey @rayrutjes ,
but the same algolia module work for one theme.
![untitled](https://user-images.githubusercontent.com/31465231/31606777-a7e1f6b6-b287-11e7-98b7-9c75e7c01b4c.png)

**Comment by Haroenv** [comment]
Hey @balwant20, thanks for opening this issue. Can you share the code that's used to generate this search?

**Comment by vvo** [comment]
@balwant20 Send an email to support@algolia.com and we will handle it. This is not a particular issue of this repository.

Thanks!
