### ISSUE TITLE
DeleteBy and DeleteByQuery methods are swapped

### ISSUE THREAD

**Issue by yeehaa123** [algolia/algoliasearch-client-javascript#640]
Whenever I use the DeleteBy method, I get the following error:

"DeleteByQuery endpoint only supports tagFilters, facetFilters, numericFilters and geoQuery condition"

DeleteByQuery followed by a query on the other hand, works but gives me a deprecation error.

**Comment by Haroenv** [comment]
Hey @yeehaa123, the deleteByQuery method works with a query, but is deprecated. The deleteBy method is the new version, but doesn't support a simple query, because it can cause more deleted than expected. So for that reason, the error is correct, since the new endpoint doesn't support queries. 

The old behaviour worked by calling `browse` on an index with those parameters and then removing them. This is not _atomic_ since other operations can happen in between the time you start removing and when you're done removing. This method still exists (albeit deprecated), but will be removed in a future major version. In that case you can replicate the current deprecated behaviour.

For which use case are you needing a query that can't be done with a different parameter?

**Comment by Haroenv** [comment]
>So the `deleteBy` is made to atomically and predictably remove records matching some criteria. And the only reliable criteria are filters (facet/tag filters or numeric filters, or geo distance). A text query is not reliable as many factors can influence it (typo tolerance, synonyms, min proximity, etc.).
