### ISSUE TITLE
change NODE_ENV to "development" from "debug" or check both

### ISSUE THREAD

**Issue by gdi2290** [algolia/algoliasearch-client-javascript#644]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
currently the codebase looks for "debug" while most libs check for "development"

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

**Comment by Haroenv** [comment]
Hey @gdi2290, we do that because they aren't development warnings, but rather when something is seriously wrong (in case you have an issue, you'd enable `DEBUG=algoliasearch`, or `NODE_ENV=debug`). When that environment is enabled, there will be console messages for every operation, which is probably not what you want.

Is there any issue you have with using `debug` for those use cases?

**Comment by gdi2290** [comment]
so long as it's documented `DEBUG=algoliasearch` it's kool

**Comment by Haroenv** [comment]
Perfect!
