### ISSUE TITLE
searchForFacetValues with filters parameter doesn't seem to work with an array of objects

### ISSUE THREAD

**Issue by ThomasHaddad** [algolia/algoliasearch-client-javascript#658]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Considering the following object indexed: 
```
{
  tools: [
    {
      name: 'foo',
      reference: 'bar'
    },
    ...
  ]
}
```
When using `searchForFacetValues` with `filters` with value such as `"tools.reference:bar"`, it keeps on retrieving every facet matching the query without considering the reference.

Here is a jsfiddle where you can reproduce it: https://jsfiddle.net/shawarma/gabn7ke3/11/

**Comment by Haroenv** [comment]
Thanks for the great example!

Do you mean that if SFFV is called, the responses also have results from `tools.reference:ci` when you're searching and `tools.reference:backend`? Just trying to make sure I understand it correctly

**Comment by ThomasHaddad** [comment]
Hi,

Yes this is exactly what i meant, i expected to retrieve only facets from one kind of reference, and not the others.

**Comment by ercolanelli-leo** [comment]
Hi there,

Allow me to jump in! I was unable to reproduce this issue, and everything seems to be working as expected inside the small python script. Do you see anything I am *not* doing as you are doing that may explain the difference in behavior we are observing?

```python
import json
import sys
import time

from algoliasearch import algoliasearch


client = algoliasearch.Client('<APPID>', '<API KEY>')
index = client.init_index('<INDEX>')

client.delete_index('<INDEX>')
index.set_settings({
    'attributesForFaceting': ['searchable(color)', 'tools.reference']
})

task = index.add_objects([
    {
        'color': 'blue',
        'tools': [
            {'reference': 'a'},
            {'reference': 'b'}
    ]}, {
        'color': 'red',
        'tools': [
            {'reference': 'c'},
            {'reference': 'd'}
    ]}, {
        'color': 'yellow',
        'tools': [
            {'reference': 'a'},
            {'reference': 'c'}
    ]}
])

index.wait_task(task['taskID'])

# Correctly prints:
# {
#   "facetHits": [
#     {
#       "value": "blue",
#       "highlighted": "blue",
#       "count": 1
#     },
#     {
#       "value": "yellow",
#       "highlighted": "yellow",
#       "count": 1
#     }
#   ],
#   "exhaustiveFacetsCount": true,
#   "processingTimeMS": 1
# }
res = index.search_for_facet_values('color', '', {'filters': 'tools.reference:a'})
json.dump(res, sys.stdout)
print()

# Correctly print:
# {
#   "facetHits": [
#     {
#       "value": "red",
#       "highlighted": "red",
#       "count": 1
#     }
#   ],
#   "exhaustiveFacetsCount": true,
#   "processingTimeMS": 1
# }
res = index.search_for_facet_values('color', '', {'filters': 'tools.reference:d'})
json.dump(res, sys.stdout)
print()
```

In the meantime, is there any chance there may be a typo in the filter you are using?

**Comment by klacointe** [comment]
Hello,

It seems that `tools` is an Object in the submitted issue, and this is an array of objects in our python example.

see https://gist.githubusercontent.com/ThomasHaddad/039342cd7ff01ff29fe24ecb3f7fbfba/raw/cb0a90c0456d6da3140acbbf248636a7dbaf6120/tools.json

**Comment by ThomasHaddad** [comment]
Hello,

Thanks for your example @ercolanelli-leo. There difference is that you are searching for a facet `color` which is outside the `tool` object. In my provided data, both are inside the tool object.

**Comment by ercolanelli-leo** [comment]
Hi @ThomasHaddad 

Sorry for the delay in my answer, looks like I missed the notification about your reply.
After another example and some thoughts, I think I get your issue, while I didn't earlier.
What you are experiencing is not a bug. I won't go as far as saying it's a feature, but it's more of a limitation than an unexpected behavior.

The granularity of the results, in Algolia, is at the "record" level, not at the array element. If one of the tools of the record matches the filter, it means that all the names inside the tools array of the records will be returned.

With an example:
```
{
    color: 'black',
    tools: [
        {reference: 'a', name: 'a'},
        {reference: 'b', name: 'b'}
    ]
}
```

If the filter is `tools.reference:a`, and you are performing a `searchForFacetValues` on `tools.name`, you will still be retrieving `b`, because `b` and `a` are still in the same `record` (despite not being in the same array object inside this record).

If you want to avoid this behavior, you will have to create a different record for each nested tool.
```
[
    {reference: 'a', color: 'black', name: 'a'},
    {reference: 'b', color: 'black', name: 'b'}
]
```

Let me know if you have additional questions.
