### ISSUE TITLE
Proxy requests through the server

### ISSUE THREAD

**Issue by bkniffler** [algolia/algoliasearch-client-javascript#659]
**Do you want to request a *feature* or report a *bug*?**
Feature

Currently, you can either use the client on your API endpoints (serverside, great for control over data) OR clientside (great for using search widgets). I'd love to have the possibility to use the library on both sides, and having the server work as a proxy, allowing to transform data before returning it to the client. This would be great to protect the algolia API with authentication and authorization and to filter data or disallow access altogether if required.

It seems like the client currently misses the possibility to define an endpoint or a function (returning promise or using callback to retrieve values) instead of using an apiKey and appId to connect to algolia directly.

```jsx
// Client
const getData = (body) => {
  return fetch('/api', body).then(req => req.body());
}
<InstantSearch
   fetcher={getData}
>
</InstantSearch>

// Server
server.post('/api', (req, res, next) => {
   if (req.isAuthenticated()) {
      return algoliasearch. search(req.body, (err, result) => {
           if (err) return next(err);
           res.json(result)
      })
   } next(new Error('Not authenticated'))
} )
```

Would this be feasible? Does this make sense to you?

**Comment by Haroenv** [comment]
Hey @bkniffler, this is currently not possible, but it is something that will probably be possible with the architecture we're working towards, and we'll definitely keep you in the loop with what our ideas are. 

However, since you seem to just be doing `search` in your backend after checking if the request is authenticated, did you check out [secured api keys](https://www.algolia.com/doc/tutorials/security/api-keys/secured-api-keys/how-to-restrict-the-search-to-a-subset-of-records-belonging-to-a-specific-user/#before-starting)? That should keep the requests fast (since they don't need to do another hop to your backend), but at the same time allow you to make sure people only are able to request what they should be able to. 

cc @vvo and @francoischalifour who are working on this idea in the future

**Comment by bkniffler** [comment]
Ah, I didn't know the secured api keys existed, very neat. I still think it'd be great to proxy for more fine grained control (e.g. ACL rules that are already in place in the nodeJS API, data transformation, field-level access). Then we'd have either full-comfort (client with search API key), mixed (generate secure keys server side and use search document fields to control access) or full-control (proxy data through server and do whatever you like).

**Comment by Haroenv** [comment]
Just to be clear on this, the reason we didn’t historically allow for this, is because it will incur another hop and inevitably a significant latency increase. We do hear you for the usecase though, and will are working towards making this possible

**Comment by Haroenv** [comment]
A workaround you can do now, is passing `algoliaClient` as a prop to `<InstantSearch />`, it should have the methods `addUserAgent` and `search([]): Promise<Object>`. Further discussion about this can be done on the repository of React InstantSearch

Beware that this is not a documented solution and definitely a workaround

**Comment by bkniffler** [comment]
Ah, thats some info I've been looking for, thanks for the hint. I thought that algoliaClient is part of the algoliasearch package and used by instantsearch under the hood. I'll definitely look into this :)

**Comment by Haroenv** [comment]
Closing this, as it has a workaround and isn't only for this module
