### ISSUE TITLE
Incorrect content type header being used

### ISSUE THREAD

**Issue by percyhanna** [algolia/algoliasearch-client-javascript#667]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
API requests are sent using incorrect `Content-Type` of `application/x-www-form-urlencoded` for JSON content.

**Headers**
![screen shot 2018-02-20 at 10 03 39 am](https://user-images.githubusercontent.com/125077/36437894-899376ec-1625-11e8-98e0-9762a882db00.png)

**Body**
![screen shot 2018-02-20 at 10 03 33 am](https://user-images.githubusercontent.com/125077/36437910-936e61d6-1625-11e8-97dd-81b244223957.png)

**What is the expected behavior?**
The `Content-Type` header would reflect the actual content type of the body. In this particular case, it should be `application/json`. Or if `application/x-www-form-urlencoded` is actually preferred, then the body should be encoded using that format.

This also implies the API servers are not properly parsing requests. The request demonstrated above should fail with a 400/4xx error, since `{"params":"query=pdf"}` is not a valid form encoded value.

**Comment by Haroenv** [comment]
This is actually on purpose to keep the requests being simple requests. Our API can handle with this format, and it avoids an extra OPTIONS request. Read more here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

I’ll close this ticket because we aware and it’s on purpose. Feel free to ask more info

**Comment by vvo** [comment]
@percyhanna Aside from @Haroenv response, did you experiment any issue by having the JavaScript client sending those particular headers? Thanks

**Comment by percyhanna** [comment]
That makes sense, and I didn't run into any other issues. The issue was mainly raised beacuse it causes bugs in developer tools when inspecting the network requests, since the payload is not in the format claimed by the `Content-Type` header. I just thought perhaps the request could be submitted with a `application/x-www-form-urlencoded` formatted payload, instead of falsifying the request.

**Comment by mjeanroy** [comment]
Hi,
May I ask you to consider adding an option to specify that the `Content-Type` header should be set to `application/json`?

I would like to use algolia with a kind of proxy on my server. I'm currently using the `hosts` option to specify that the client should request my server, to be able to call the "real" endpoint. It allows me two things:

- Not exposing my API token.
- Not being blocked by some anti-tracker (some adblockers / anti-trackers) are blocking some cross origin requests for some users of my application.

Currently, using `application/x-www-form-url-encoded` break the parsing of my reverse proxy, since it does not see that the content is, in fact, valid JSON. Currently there is no way to override this `Content-Type` header since it is hardcoded in the js client.

Would you be open to add an option for that (and I can submit a PR if you want)?

**Comment by vvo** [comment]
@mjeanroy I believe we won't add such an option because it can be solved another way: is it possible for you to not even use the JavaScript API client on the frontend but just use it on your backend? So you can proxy anything you want. Also if you're using InstantSearch, you can follow the backend implementation here: https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/js/.

Let me know how it goes.

**Comment by mjeanroy** [comment]
@vvo I understand. In fact, we are using the the wrapper [Algolia Places](https://github.com/algolia/places/) around the javascript client, so it's not an easy task to rewrite this kind of plugin (definitely doable but that's a lot of work, as you may know).

Maybe the `hosts` option was not intended for this use case, but I thought changing the target host was an elegant solution to hide api keys and to not trigger cross domain requests. Everything works fine except this `Content-Type` hack that does not work in my case (the fact that it is hardcoded make it impossible to change anything).

Thanks for the work behing algolia places btw.
