### ISSUE TITLE
Search client can't be initialized without explicitly passing in protocol

### ISSUE THREAD

**Issue by adriennedomingus** [algolia/algoliasearch-client-javascript#672]
We don't explicitly pass protocol in when initializing our search client - this has worked up until now, but is now throwing an error, causing all search on our site to not work. 

Looks specifically related to [this](https://github.com/algolia/algoliasearch-client-javascript/commit/f3f30c88c4882432b454cc438bb9f7742aa714f1) commit

**Comment by vvo** [comment]
Hi @adriennedomingus this should be solved right now we pushed updates to solve that, can you provide me the line you are using to add the JavaScript client on your website? Thanks

**Comment by adriennedomingus** [comment]
Hi @vvo When we saw the issue we were using `<script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>`, but just pushed out a change to use `<script src="//cdn.jsdelivr.net/algoliasearch/3.24.7/algoliasearch.min.js"></script>`, since we've had issues before and that's a known safe version for us - so we're currently working again, but not on the most recent version

**Comment by vvo** [comment]
Hi @adriennedomingus 

we published a bad fix on our JavaScript client (that you are using) that triggered this issue on your side. Sorry about that.
​
​We have published a new version but it takes time to propagate to Algolia scripts inserted like <script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js">></script>,
​it is currently being propagated and your website should be working again in the coming minutes.
​
In the meantime, as a better fix, can you update your website scripts so that you change:
​- https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js
to
​- https://cdn.jsdelivr.net/algoliasearch/3.25.1/algoliasearch.min.js​
​
​By doing so you will ensure that if it's working right now it will always be working because there won't be anymore any
​auto update to your website.
​
On behalf of Algolia I apologise for this current issue and hope you can update your code accordingly for this
​to never happen again.
​
​Let me know if you have further questions.

**Comment by vvo** [comment]
This is now resolved, if you have more questions @adriennedomingus send them over to support@algolia.com
