### ISSUE TITLE
client.moveIndex fails silently when passed incorrect type

### ISSUE THREAD

**Issue by jackellenberger** [algolia/algoliasearch-client-javascript#673]
Algolia library version: 3.24.12
Node version: v4.8.4

**What is the current behavior?**

When client.moveIndex() is passed an index as its first parameter instead of the string name of that index, the command completes successfully but nothing is moved.

The minimal version of this issue is below:

```js
var algoliaSearch = require('algoliasearch');
var client = algoliaSearch(APP_ID, APP_KEY);

var tempIndexName = 'temp-index';
var existingIndexName = 'existing-index';
var tempIndex = client.initIndex(tempIndexName);
var indicies = [{}, {}]; //etc
var tempIndex;

client.copyIndex(existingIndexName, tempIndexName).then(() => {
    tempIndex = client.initIndex(tempIndexName);
    return tempIndex.addObjects(indices)
}).then(() => {
    return client.moveIndex(tempIndex, existingIndexName)
}).then(() => {
    console.log('done');
    return;
}).catch(err => {
    console.log('error!');
    return err;
});

```

**What is the expected behavior?**

In the above example I would expect to see `error!` logged, then an typeError returned, but instead we see `done` logged out. In the Algolia UI, the existing index will say `updated 1 minute ago`, but none of the indices will have changed.

It seems from the source code like this might just be standard behavior for this library, so maybe it's not really an issue, but it is something that got me hung up for a while, so maybe if nothing else the expected inputs should be documented [with the function](https://www.algolia.com/doc/api-reference/api-methods/move-index/).

**Comment by Haroenv** [comment]
I notice that you wrote `var indicies`, but use the variable `indices`. Is it possible that it's related to this (since `indices` is undefined, which is a valid value). 

EDIT: ah I see what you mean here, there should be an error for the input of the object instead of string

**Comment by Haroenv** [comment]
So the bug happened because of two reasons: 

1. the index object was used, instead of the string
2. since we assumed it was a string, `encodeURIComponent` returned `[object Object]` (`"%5Bobject%20Object%5D"`)
3. since that is a valid index name, Algolia (the backend) didn't complain
4. since the index doesn't exist, the operation is considered void and does nothing

The correct code in this case would've been this: 

```js
const algoliaSearch = require('algoliasearch');
const client = algoliaSearch(APP_ID, API_KEY);

const tempIndexName = 'temp-index';
const existingIndexName = 'existing-index';
const tempIndex = client.initIndex(tempIndexName);
const objects = [{}, {}]; // etc

client
  .copyIndex(existingIndexName, tempIndexName)
  .then(() => tempIndex.addObjects(objects))
  .then(() => client.moveIndex(tempIndexName, existingIndexName))
  .then(() => {
    console.log('done');
    return;
  })
  .catch(err => {
    console.log(err);
    return err;
  });
```

I've let this know to our core engine team to discuss why this didn't throw an error (backend) and the reason is this:

If you do atomic reindexing, you will typically do a sequence like:
1. Add records to a nonexistent index
2. Move that index to its destination
If you don’t want to wait after 1, then you are going to issue the move operation before the index actually exists. This is why no error can be thrown for copying a non-existing index

I opened a separate issue for type checking, since it's a bigger issue than just this one method. For now I can't say much more than be careful which method you write with which arguments

**Comment by jackellenberger** [comment]
Great, thank you!
