### ISSUE TITLE
React Native - Requiring unknown module "undefined"

### ISSUE THREAD

**Issue by zachrnolan** [algolia/algoliasearch-client-javascript#681]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When searching quickly and tapping elsewhere on a component, we are seeing the following error:

![react_native_debugger_-_connected__port_8081_](https://user-images.githubusercontent.com/66614/38579589-5ea13c2c-3cbc-11e8-93fc-cff9e36bd353.jpg)

I've found an issue on react-native that may shed more light on this issue: 
- https://github.com/facebook/react-native/issues/18179

**What is the expected behavior?**

App should not crash.

**Other Details**
"algoliasearch": "^3.26.0",
"react": "^16.3.0-alpha.1",
"react-native": "0.54.1",

**Comment by samouss** [comment]
Thanks a lot for the notice! It looks like [the issue](https://github.com/facebook/react-native/issues/18179#issuecomment-373046767) arise when we import a module with the same path multiple times in the same file. By looking at the stack trace it happens with the `clone` function in [`AlgoliaSeachCore`](https://github.com/algolia/algoliasearch-client-javascript/blob/2533c50a9588f5eccff1ebcf9716f476451d9f60/src/AlgoliaSearchCore.js). In this file we import `clone` multiple times, because we scope the imports at the function level. I don't know the reason behind that? Maybe @vvo knows?

According to the issue, the problem is present on the version `>= 0.54.x` of React Native. With a version `<= 0.53.x` it should work (I didn't test though). You can stick to this version until we find a way to patch the library.

**Comment by Haroenv** [comment]
To be honest, this sounds like a bug in metro(?), rather than our library. I think we can change the imports to be top-level though, although that would mean they get imported at all times, and not just when you need the file. I think it might also have an impact on bundle size, but not sure if bundlers actually make use of the fact that `require` can be done in other spots than top-level.

Maybe we can also use the `clone` require top-level because it's used multiple times?

**Comment by samouss** [comment]
Yes it's definitely an issue in metro. It might have a (little) impact Node because the import will be executed when the file is required instead of when the function is called. But for the bundled files it should not impact the size (since the import are resolved at bundle time). We can even gain a little bytes since it will remove some lines.

**Comment by zachrnolan** [comment]
Hey @samouss and @Haroenv, thanks for the quick replies. We are having a good amount of crashes in our app. Do you have any ETA for a fix? If it's coming soon, I can hold off downgrading RN. Appreciate the response!

**Comment by Haroenv** [comment]
We’ll need to investigate this deeply, making it a priority next week ok?

**Comment by zachrnolan** [comment]
That sounds great. Thanks again for making this a priority.

**Comment by Haroenv** [comment]
So I took a look into this, the reason was indeed a bug in metro. You can see the commit in React Native master that bumps metro here: https://github.com/facebook/react-native/commit/b02b1670d65118c333d3e0b83ddc99d2dc39dbed

What you can do is use the yarn resolution feature (https://yarnpkg.com/en/docs/selective-version-resolutions), or adding 0.30.2 as a dependency to your app to resolve the correct version of metro, with the fix. 

Feel free to reopen if you tried that and it still didn't work.

**Comment by zachrnolan** [comment]
@Haroenv I tried adding resolutions to our project:

    "resolutions": {
        "metro": "^0.30.2",
        "metro-core": "^0.30.2"
    }

However, we are getting an error when the bundler starts (doesn't even give us a stack trace): 
`Cannot read property 'length' of undefined`

If we don't go the resolutions route, but add metro and metro-core to our project package.json, that will not change the version of metro that RN uses right? 

Any pointers would be greatly appreciated, thanks again!

**Comment by Haroenv** [comment]
You could try that out, but if you could give us access to a minimal reproduction of the problem, it would save a lot of time :). Otherwise I think the easiest would be to downgrade, wait, and upgrade

**Comment by GeoffreyPlitt** [comment]
Any update on this fix? It will affect every react-native developer who uses this soon...

**Comment by Haroenv** [comment]
Did you try using the specified metro version @geoffreyPlitt? AFAIK this has been fixed on RN’s side, just not released yet. Otherwise you can stay on RN 0.53.x rather than 0.54.x and upgrade immediately to 0.55.x when that’s available :) if you have a project in which this can be reproduced, it would be very useful!

**Comment by samouss** [comment]
This issue arise with the version 0.54.x of React Native. To solve the issue you should either upgrade on 0.55.x or downgrade on the 0.53.x.
