### ISSUE TITLE
Expose AlgoliaSearchError

### ISSUE THREAD

**Issue by Jerska** [algolia/algoliasearch-client-javascript#683]
I'd like to be able to conditionally check if I received an `AlgoliaSearchError`, using:
```js
const AlgoliaSearchError = ???;
try {
  await index.getSettings();
} catch (e) {
  if (e instanceof AlgoliaSearchError) {
    ...
  }
}
```
To my suprise, I realized that I couldn't find any reference to the class.
Could we expose it at the top level `module.exports` ?

**Comment by Haroenv** [comment]
It’s in it’s own file, so I think you’ll be able to import it. Otherwise I think err.name should be “AlgoliaSearchError”. Did you try those things?

**Comment by Jerska** [comment]
I've just opened two potential PRs to do this.

> I think you’ll be able to import it

While you're correct, this would not be doable in front-end builds and might not be forward compatible in case you'd like to move it from a subfolder to another, etc.

> `err.name` should be “AlgoliaSearchError”

This would indeed work.
Wouldn't this be considered bad practice though?

**Comment by Haroenv** [comment]
I’ve seen this pattern to detect other types of errors (e.g. AbortError) and i can’t see how it would be removed in Minified builds for example because the name property is explicitly set. 

Now that I think about it, I’m not sure if AlgoliaSearchError should be public/top-level API, since that would prevent us from ever removing if it would make sense to do so. We can discuss it in person too :)

**Comment by vvo** [comment]
@Jerska I can definitely understand the need for this, do you have any other library examples in JavaScript that are providing this kind of functionality?

The code example you have is maybe not the exact issue you have in your code? Maybe you have a top level loop that is not aware of what's going on inside it and you want to deal with errors at the top level? In your example the error can only be about Algolia since that's the ony call being done no?

**Comment by Jerska** [comment]
Yes, but there are multiple issues that could arise here. My attempt here is to detect if an index exists in Algolia.
The only way I know to do this is to run a `getSetting()` or `search()` on it and check if the HTTP code is 404.

Here are all the other errors that can arise which I don't want to catch:
- AlgoliaSearchError but 403
- AlgoliaSearchError but 500
- Network down
- SSL failing

Here's how I do this in Shopify with the ruby client (which exposes `Algolia::AlgoliaSearchError`)

https://github.com/algolia/algoliasearch-shopify/blob/b34c23b6e1d8eb5d9f0c2d18bd26b9d65cde31e8/app/models/algolia_config.rb#L209-L221

Funnily enough, I didn't find much occurences of this.
This is a really common pattern in most OOP languages (Ruby even has a shorthand syntax for `catch`ing on a specific Error type).

Probably because ES6 is still "new" and `extends` still doesn't fully work when transpiled: https://stackoverflow.com/questions/33870684/why-doesnt-instanceof-work-on-instances-of-error-subclasses-under-babel-node .

I did find one example though: `webpack` exposes `WebpackOptionsValidationError`.
Exposed in https://github.com/webpack/webpack/pull/3218 without much explanation.

**Comment by vvo** [comment]
This is a super interesting discussion and one where the community never agreed on, compare it to the callback convention, everyone agreed that (err, res) was a defacto standard.

As for checking for errors, using instanceof or checking err.name is spread amongst the community.

What could influence our choices would be how JavaScript typings can influence the choice or even how things are documented on big libraries.

For now as we have seen, you can rely on err.name and that's the public API of the module.

**Comment by Jerska** [comment]
Sounds good to me. :)
