### ISSUE TITLE
Per request headers

### ISSUE THREAD

**Issue by jacksbox** [algolia/algoliasearch-client-javascript#774]
I have a general question for which I can't find an answer in the documentation:
Is it possible to set additional headers for individual request (setExtraHeaders does not work, as it sets it for every request)?

**Comment by Haroenv** [comment]
It’s unfortunately not possible with this version of the client. Usually you should be able to set & after the query unset

**Comment by jacksbox** [comment]
@Haroenv thank for the info. 
Set/Unset is not possible for me right now: in my application requests use the same client right know and it can be that multiple request will be done in parallel... so undesired side effects is a real danger. 

Bit OT, Is there another way to send the userToken instead of `X-Algolia-UserToken`?

**Comment by Haroenv** [comment]
I understand, which is also why we want to solve this in the next major version of the JS client. It proved to be impossible without breaking changes to support sending headers. 

A userToken can also be passed as a regular query parameter: https://www.algolia.com/doc/api-reference/api-parameters/userToken/?language=javascript

here's an example: https://codesandbox.io/s/javascript-client-app-jt1wi

I'll close this issue now, since there's an alternative solution possible.
