### ISSUE TITLE
discussion: no documentation on how to prevent CSRF to pass PCI compliance

### ISSUE THREAD

**Issue by RichardBronosky** [algolia/algoliasearch-client-javascript#865]
My [search for CSRF](https://github.com/search?q=org%3Aalgolia+csrf&type=Code) revealed that the CSRF NPM package [might be vicariously required](https://github.com/algolia/react-instantsearch/blob/bfbdcfe01a40080030f07a16e0aea9531a8db134/examples/react-native-query-suggestions/yarn.lock#L2004). Then search for token revealed that you have a [userToken concept](https://www.algolia.com/doc/api-reference/api-parameters/userToken/).

What I can't figure out is:
How do we implement CSRF on Algolia search boxes?

I really don't care about the security, but the PCI audit does.

**Comment by Haroenv** [comment]
The yarn.lock you linked in case isn't used in the library, but rather in a devdependency. Could you explain what the goal of the CSRF is in your use case?

**Comment by RichardBronosky** [comment]
Even though I know that CSRF against the Algolia search form is not a danger, our quarterly PCI compliance audit requires us to prove it and get granted an exception. All over again each quarter.
I'd like to implement something like: https://en.wikipedia.org/wiki/Cross-site_request_forgery#Cookie-to-header_token
The idea would be that the form submission would come with a cookie and a header that must match. If they do not, reject the search.

**Comment by Haroenv** [comment]
Could you  clarify how there's a  form submission for a regular Algolia search? Normally if you are using the js client, you'd search frontend without ever submitting a  form (only sending XHRs). If you _are_ submitting forms, then this should be done in your own backend, since the search can not know what a user has access to. I advise you to maybe take a look at secured api keys: https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/. You can add a set time to the key and revalidate before it expires. This way a stolen api key only stays useful as long as the user is logged in.

**Comment by nunomaduro** [comment]
We don't plan to change things on the `v3.x`. And this is done on the `v4.x`.

**Comment by nunomaduro** [comment]
Because this issue seems to be inactive for quite some time now, I've closed it. If you feel this issue deserves some attention feel free to reopen it.
